// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      /*case TargetPlatform.iOS:
        return ios; */
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJL72NEgRn7wuG1txttFsVX30efPsixZw',
    appId: '1:1027746126649:web:55de2274feec87939626e8',
    messagingSenderId: '1027746126649',
    projectId: 'chef-palette',
    authDomain: 'chef-palette.firebaseapp.com',
    storageBucket: 'chef-palette.firebasestorage.app',
    measurementId: 'G-7963J21YX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDezjkKndVn_CjHV1v6Ovk949ngZ98wDIA',
    appId: '1:1027746126649:android:8f6faa60b077ea259626e8',
    messagingSenderId: '1027746126649',
    projectId: 'chef-palette',
    storageBucket: 'chef-palette.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqhrJIPywxUyWxxwpKC1nkJjSMMZrlIY',
    appId: '1:1027746126649:ios:d1a3b4592d30ad4f9626e8',
    messagingSenderId: '1027746126649',
    projectId: 'chef-palette',
    storageBucket: 'chef-palette.firebasestorage.app',
    iosBundleId: 'com.chefpalette.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADqhrJIPywxUyWxxwpKC1nkJjSMMZrlIY',
    appId: '1:1027746126649:ios:d1a3b4592d30ad4f9626e8',
    messagingSenderId: '1027746126649',
    projectId: 'chef-palette',
    storageBucket: 'chef-palette.firebasestorage.app',
    iosBundleId: 'com.example.chefPalette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJL72NEgRn7wuG1txttFsVX30efPsixZw',
    appId: '1:1027746126649:web:8e90ebe9e489101d9626e8',
    messagingSenderId: '1027746126649',
    projectId: 'chef-palette',
    authDomain: 'chef-palette.firebaseapp.com',
    storageBucket: 'chef-palette.firebasestorage.app',
    measurementId: 'G-68EN3XXT0R',
  );
}
